### ISSUE TITLE
Child node created although it is the same as the parent node

### ISSUE THREAD

**Issue by rmkane** [The-Penultimate-Defenestrator/wikipedia-map#15]
When I query for "[The Smashing Pumpkins](https://en.wikipedia.org/wiki/The_Smashing_Pumpkins)," and click on "[James Iha](https://en.wikipedia.org/wiki/James_Iha)," a child node is created for "[The Smashing Pumpkins](https://en.wikipedia.org/wiki/The_Smashing_Pumpkins)." Since the child IS the same as the parent, the node should not be created or at least filtered out after the list comes back.

![Graph: The Smashing Pumpkins -> James Iha](http://i.imgur.com/llSeiIX.png)

**Comment by controversial** [comment]
Thanks for reporting. This is essentially the same as #2 

So why this occurs is because wikipedia pages have multiple aliases. There are multiple different links that go to "The Smashing Pumpkins."

When you put in "The Smashing Pumpkins," your input is **directly URI encoded**. This replaces the spaces in your input with the appropriate code. Therefore, the URL that Wikipedia Map looks at is https://en.wikipedia.org/wiki/The%20Smashing%20Pumpkins, with percent codes replacing spaces.

The article for "James Iha" links to a different URL that points to the same page: https://en.wikipedia.org/wiki/The_Smashing_Pumpkins. Since one uses spaces and one uses percent codes, Wikipedia Map registers these as different pages, even though they redirect and resolve to the same thing. 

I'll close this since it's the same problem as #2 (although that's not inherently obvious without looking at URLs more closely). Thanks a lot for reporting this, though. I'm gonna try to find a short-term solution to this problem soon.

**Comment by controversial** [comment]
This should be fixed now. I haven't implemented a full fix, but simple cases like these should be prevented now.
