### ISSUE TITLE
Node shows edge to self

### ISSUE THREAD

**Issue by lukaskollmer** [The-Penultimate-Defenestrator/wikipedia-map#21]
When you enter `facebook` as one of your search terms, the main topic node will show an edge to itself

![](http://cdn.kollmer.me.s3.amazonaws.com/embed/wikipedia-map_edge_to_self.png)

**Comment by controversial** [comment]
normally, that would be because the article contained a link back to itself. However, in this case, it looks like Facebook links to "face book". To try and combat duplicate nodes (sometimes cased by spelling differences), Wikipedia map removes spaces and sees these as the same article. I'll try to fix soon.

**Comment by controversial** [comment]
I think I'll look into whether Wikipedia assigns unique IDs to pages, then I could use these. The most major restriction with Wikipedia Map as a whole is that I can't perform any kind of operations on each created node, because that would slow down expansion a lot. Speed is hard to get right on this.

The easiest fix for this would be to forbid nodes linking to themselves altogether, I think. The whole ID system used now is pretty unreliable.

Maybe the MediaWiki API provides methods for getting IDs for a whole bunch of pages at once. I could fix if this was a thing.

**Comment by controversial** [comment]
“facebook” and “face book” are now treated separately, and there's a much better mechanism for resolving duplicates now. I don't think there are very many cases where a node would link to itself when it's not supposed to, besides some extreme edge cases.
