### ISSUE TITLE
Not showing all wikipedia article links

### ISSUE THREAD

**Issue by Almyk** [The-Penultimate-Defenestrator/wikipedia-map#35]
When searching for https://en.wikipedia.org/wiki/San_Diego_Comic-Con only one node is created, but there are over 800 wikipedia article links in that page.

**Comment by controversial** [comment]
I just deployed a fix for the bug that caused "Geographic Coordinate System" to be the only node created from "San Diego Comic-Con" and a few other articles. Now, the node properly expands into three sub-nodes:

<img width="393" alt="screen shot 2018-05-21 at 11 16 47 pm" src="https://user-images.githubusercontent.com/10377391/40340485-1d9dd648-5d4d-11e8-9806-e6c7b67cb3d1.png">

You should note that Wikipedia Map's decision not to expand all 800 links is by design; the tool is designed to only expand the links in the first paragraph. You can read more about this decision [in the README](https://github.com/controversial/wikipedia-map/blob/master/README.md#functional).
